config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope :process do
    match '/run', to: 'process#run', via: [:get, :post], as: :process_run
    get '/finished', to: 'process#quest_finished', as: :process_quest_finished
  end

  scope :quests do
    get '/', to: 'quests#index', as: :quests
    get '/show/:id', to: 'quests#show', as: :quest_show
    get '/new', to: 'quests#new', as: :quest_new
    post '/new', to: 'quests#create', as: :quest_create
  end

end

app/models/quest.rb
class Quest < ActiveRecord::Base

  # Associations :::::::::::::::::::::::::::::::::::::::::::::::::
  belongs_to :user
  has_many :questions
  has_many :quest_finisheds
  accepts_nested_attributes_for :questions, :allow_destroy => true

  # Validates :::::::::::::::::::::::::::::::::::::::::::::::::::
  validates :caption, :description, :time_quest, presence: true
  validates_numericality_of :time_quest

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :authenticate_user!
  before_action :teacher?, only: [:new, :create]

  def index
    @layout_title = 'Quests'
    @quests = Quest.order(:created_at).reverse_order.all
  end

  def show
    @quest = Quest.where(id: params[:id]).last
    unless @quest
      error_404
      return false
    end

    @quest_finished = QuestFinished.where(user: current_user, quest: @quest).last

    if current_user.role == User::ROLE_STUDENT
      unless @quest_finished
        session[:quest_run] = { quest_id: @quest.id, quest_end_time: nil, current_question: 1 }
      else
        @questions = @quest.questions
      end
    end
  end

  def new
    @quest = Quest.new
    @quest.questions.build
    @quest.questions.last.question_options.build(test_answer: 1)
  end

  def create
    @quest = Quest.new(par_quest)
    @quest.user = current_user

    if @quest.save
      redirect_to quest_show_path(@quest)
    else
      render :new
    end
  end

  private

  def par_quest
    params.require(:quest).permit([:caption,
                                   :time_quest,
                                   :description,
                                   :test_answer,
                                   { questions_attributes: [:txt,
                                                            :question_type,
                                                            :answer,
                                                            :test_answer,
                                                            { question_options_attributes: [:txt] }] }])
  end

end

app/views/quests/index.html.erb
<% if current_user.role == User::ROLE_TEACHER %>
  <%= link_to 'Add quest', quest_new_path %>
<% end %>

<div class="row marketing">
  <% @quests.each do |quest| %>

    <h4><%= quest.caption %></h4>
    <p><%= quest.description.truncate(200, omission: '') %> <%= link_to 'Open', quest_show_path(quest)%></p>

  <% end %>
</div>

app/views/quests/new.html.erb
<%= form_for @quest, url: quest_create_path do |f| %>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_field :caption, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => 'form-control', :rows => '5' %>
  </div>

  <div class="questions" id="wrapper_questions" data-option-now="<%= f.object.questions.size %>">
    <%= f.fields_for :questions do |question| %>
    <div class="panel panel-default question-panel">
      <div class="panel-heading">Question - <%= question.index+1 %></div>
      <div class="panel-body">
        <div class="form-group">
          <%= question.text_area :txt, :class => 'form-control', :rows => '5' %>
        </div>

        <div class="form-group">
          <%= question.select :question_type, question_type_options(question.object.question_type), {}, { class: 'form-control selectpicker select_question_type', 'data-id': question.object_id } %>
        </div>

        <div id="question-type-one_<%= question.object_id %>" style="display: <%= question.object.question_type == Question::ONE_ANSWER ? 'block' : 'none' %>;">
          <div class="form-group">
            <%= question.text_field :answer, :class => 'form-control', :rows => '5', :placeholder => 'Answer' %>
          </div>
        </div>

        <%= question.hidden_field :question_type, :id => "question_type_#{question.object_id}" %>

        <div id="question-type-multi_<%= question.object_id %>" style="display: <%= question.object.question_type == Question::MULTI_ANSWER ? 'block' : 'none' %>;">
          <table class="table">
            <thead>
            <tr>
              <th>Option</th>
              <th>Answer</th>
              <th>Correct answer</th>
            </tr>
            </thead>
            <tbody id="question-type-multi-body_list_<%= question.object_id %>" data-options="<%= Question::LIST_OPTIONS.join('|') %>" data-option-now="<%= question.object.question_options.size %>">
              <%= question.fields_for :question_options do |type_option| %>
                <tr class="table_row_question-type-multi">
                  <td><%= Question::LIST_OPTIONS[type_option.index] %></td>
                  <td>
                    <%= type_option.text_field :txt, :class => 'form-control', :placeholder => 'Answer' %>
                  </td>
                  <td>
                    <div class="radio">
                      <label>
                        <input type="radio" name="quest[questions_attributes][<%= question.index %>][test_answer]" value="<%= type_option.index %>" <%= ((type_option.index == question.object.test_answer.to_i) ? 'checked' : '') %> >
                      </label>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <button type="button" class="btn btn-primary button_add_option" data-id="<%= question.object_id %>">Add option</button>
          <button type="button" class="btn btn-danger button_remove_option" data-id="<%= question.object_id %>">Remove last</button>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="form-group">
    <button type="button" class="btn btn-primary button_add_question" data-id="<%= f.object_id %>">Add question</button>
    <button type="button" class="btn btn-danger button_remove_question" data-id="<%= f.object_id %>">Remove last</button>
  </div>

  <div class="form-group">
    <%= f.label :time_quest, 'Time quest ', 'data-help': '(Minutes)' %>
    <%= f.text_field :time_quest, :class => 'form-control' %>
  </div>

  <%= f.submit 'Create', :class => 'btn btn-default' %>

<% end %>

app/views/quests/show.html.erb
<div class="row marketing">
  <h4><%= @quest.caption %></h4>
  <p><%= @quest.description %></p>
  <% if current_user.role == User::ROLE_STUDENT %>
    <% unless @quest_finished %>
      <%= link_to 'Start', process_run_path, class: 'btn btn-primary right' %>
    <% end %>
    <div>
      <div>The time for completion: <%= @quest.time_quest %> (min)</div>
      <% if @quest_finished %>
      <div>The time spent: <%= @quest_finished.time_spent %>(min)</div>
      <div>The true: <%= @quest_finished.percentage_true %>%</div>
      <div>The false: <%= @quest_finished.percentage_false %>%</div>

        <br><br>
        <% @questions.each_with_index do |question, index| %>
          <div class="panel panel-<%= status_panel_answer(@quest, question) %>">
            <div class="panel-heading">
              <h3 class="panel-title">Question: <%= index %></h3>
            </div>
            <div class="panel-body">
              <div><%= question.txt %></div>
              <br>

              <% if question.question_type  == Question::MULTI_ANSWER %>
                <div>Options</div>
                <div>
                  <% question.question_options.each_with_index do |question_option, index| %>
                    <div><%= Question::LIST_OPTIONS[index] %>: <%= question_option.txt %></div>
                  <% end %>
                </div>
                <br>
                <div>Answer: <%= Question::LIST_OPTIONS[question.answer.to_i] %></div>
                <div>Me answer: <%= Question::LIST_OPTIONS[me_answer(@quest, question).to_i] %></div>
              <% else %>
                <div>Answer: <%= question.answer %></div>
                <div>Me answer: <%= me_answer(@quest, question) %></div>
              <% end %>
            </div>
          </div>
        <% end %>

      <% end %>
    </div>

  <% elsif @quest.user == current_user %>
    <% @quest.questions.all.each_with_index do |question, index| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Question: <%= index+1 %></h3>
        </div>
        <div class="panel-body">
          <div>
            <%= question.txt %>
          </div>
          <br>
          <% if question.question_type  == Question::MULTI_ANSWER %>
            <div>Options</div>
            <div>
              <% question.question_options.each_with_index do |question_option, index| %>
                <div><%= Question::LIST_OPTIONS[index] %>: <%= question_option.txt %></div>
              <% end %>
            </div>
            <br>
            <div>Answer: <%= Question::LIST_OPTIONS[question.answer.to_i] %></div>
          <% else %>
            <div>Answer: <%= question.answer %></div>
          <% end %>
        </div>
      </div>
    <% end %>

  <% end %>
</div>