config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope :process do
    match '/run', to: 'process#run', via: [:get, :post], as: :process_run
    get '/finished', to: 'process#quest_finished', as: :process_quest_finished
  end

  scope :quests do
    get '/', to: 'quests#index', as: :quests
    get '/show/:id', to: 'quests#show', as: :quest_show
    get '/new', to: 'quests#new', as: :quest_new
    post '/new', to: 'quests#create', as: :quest_create
  end

end

app/views/shared/_form_errors.html.erb
<% errors.each do |error| %>
  <div class="alert alert-danger">
    <strong><%= error[0] %></strong>
    <%= error[1][0] %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<ul class="nav nav-pills pull-right">
  <li <%= request.path_info == root_path.to_s ? 'class=active' : '' %>><%= link_to 'Home', root_path %></li>
  <li <%= request.path_info == quests_path.to_s ? 'class=active' : '' %>><%= link_to 'Quests', quests_path %></li>
  <% unless current_user.nil? %>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, data: { confirm: 'Are you sure?' }) %></li>
  <% else %>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Log in', new_user_session_path %></li>
  <% end %>
</ul>

app/views/shared/_question.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= question.caption %></div>

  <div class="panel-body">
    <% unless question.image.blank? %>
      <p>
        <%= image_tag question.image.url(:thumb) %>
      </p>
    <% end %>
    <p>
      <%= question.description %>
    </p>
  </div>

  <%= multiple_questions(question, my_answer) %>
</div>

<% if show_answer %>
  <p class="color-grey">
    Answer: <%= ((question.question_type == Question::ONE_ANSWER) ? question.answer : Question::LIST_OPTIONS[question.answer.to_i]) %>
  </p>
<% end %>